# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Readme Update

on:
  push:
    branches: [ home ]
  pull_request:
    branches: [ home ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        pip install pytz
    - name: Run readme_update
      run: | 
        python script/readme_update.py --push
        
    - name: config git
      run: |
        git config --local user.email "qpyu66@naver.com"
        git config --local user.name "Bae"
        git add .
        git commit -m "readme auto update"
        
    - name: push
      uses: ad-m/github-push-action@master
      with:
        branch: ${{github.ref }}
        github_token: ${{secrets.GITHUB_TOKEN }}

